title: Udit Chauhan
logo: /assets/img/headshot.jpeg
show_downloads: false
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark # Or auto if you want it to switch with your system settings.
